const ALL_SLOTS = [
  // ── Series 20, Odd Semester ─────────────────────────────────────────────
  {
    _id: "20_sat_1",
    day: "Saturday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "ETE 4200",
    courseTitle: "Project & Thesis",
    type: "project",
    teacherInitials: ["—"],
    room: { roomLabel: "—" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sat_4",
    day: "Saturday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 4211",
    courseTitle: "ETE 4211",
    type: "theory",
    teacherInitials: ["FZA"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sat_5",
    day: "Saturday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 4215",
    courseTitle: "ETE 4215",
    type: "theory",
    teacherInitials: ["SI"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sat_6",
    day: "Saturday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 4213",
    courseTitle: "ETE 4213",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sun_1",
    day: "Sunday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "ETE 4200",
    courseTitle: "Project & Thesis",
    type: "project",
    teacherInitials: ["—"],
    room: { roomLabel: "—" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sun_4",
    day: "Sunday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "Hum 4215",
    courseTitle: "Hum 4215",
    type: "theory",
    teacherInitials: ["SI"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sun_5",
    day: "Sunday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 4225",
    courseTitle: "ETE 4225",
    type: "theory",
    teacherInitials: ["AIS"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sun_6",
    day: "Sunday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 4211",
    courseTitle: "ETE 4211",
    type: "theory",
    teacherInitials: ["FZA"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_sun_7",
    day: "Sunday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 4214",
    courseTitle: "Antenna & Propagation LAB",
    type: "lab",
    teacherInitials: ["ST"],
    room: { roomLabel: "Antenna & Propagation LAB" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_mon_4",
    day: "Monday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 4225",
    courseTitle: "ETE 4225",
    type: "theory",
    teacherInitials: ["AIS"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_mon_5",
    day: "Monday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "Hum 4215",
    courseTitle: "Hum 4215",
    type: "theory",
    teacherInitials: ["SI"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_mon_6",
    day: "Monday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 4215",
    courseTitle: "ETE 4215",
    type: "theory",
    teacherInitials: ["RTM"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_mon_7",
    day: "Monday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 4216",
    courseTitle: "DSP Lab",
    type: "lab",
    teacherInitials: ["RTM"],
    room: { roomLabel: "DSP Lab" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_tue_4",
    day: "Tuesday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 4225",
    courseTitle: "ETE 4225",
    type: "theory",
    teacherInitials: ["AIS"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_tue_5",
    day: "Tuesday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 4215",
    courseTitle: "ETE 4215",
    type: "theory",
    teacherInitials: ["RTM"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_tue_6",
    day: "Tuesday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 4213",
    courseTitle: "ETE 4213",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_tue_7",
    day: "Tuesday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 4214",
    courseTitle: "Antenna & Propagation LAB",
    type: "lab",
    teacherInitials: ["FZA"],
    room: { roomLabel: "Antenna & Propagation LAB" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_wed_1",
    day: "Wednesday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "ETE 4213",
    courseTitle: "ETE 4213",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_wed_2",
    day: "Wednesday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "ETE 4215",
    courseTitle: "ETE 4215",
    type: "theory",
    teacherInitials: ["RTM"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },
  {
    _id: "20_wed_3",
    day: "Wednesday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 4211",
    courseTitle: "ETE 4211",
    type: "theory",
    teacherInitials: ["FZA"],
    room: { roomLabel: "R 301" },
    batchScope: "all",
    series: 20,
    semester: "even",
  },

  // ── Series 21, Even Semester ─────────────────────────────────────────────
  {
    _id: "21_sat_1",
    day: "Saturday",
    startPeriod: 1,
    periodSpan: [1, 2 , 3],
    courseCode: "ETE 4100",
    courseTitle: "Project & Thesis",
    type: "project",
    teacherInitials: ["—"],
    room: { roomLabel: "—" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sat_4",
    day: "Saturday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 4115",
    courseTitle: "ETE 4115",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sat_5",
    day: "Saturday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 41XX",
    courseTitle: "ETE 41XX",
    type: "theory",
    teacherInitials: ["MKH", "RTM"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sat_6",
    day: "Saturday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 4111",
    courseTitle: "ETE 4111",
    type: "theory",
    teacherInitials: ["RKH"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sun_1",
    day: "Sunday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "ETE 4116",
    courseTitle: "Computer LAB",
    type: "lab",
    teacherInitials: ["RA"],
    room: { roomLabel: "Computer LAB" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sun_4",
    day: "Sunday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 41XX",
    courseTitle: "ETE 41XX",
    type: "theory",
    teacherInitials: ["MKH", "RTM"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sun_5",
    day: "Sunday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 4117",
    courseTitle: "ETE 4117",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sun_6",
    day: "Sunday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 4111",
    courseTitle: "ETE 4111",
    type: "theory",
    teacherInitials: ["RKH"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_sun_7",
    day: "Sunday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 4120",
    courseTitle: "Industrial Training",
    type: "lab",
    teacherInitials: ["—"],
    room: { roomLabel: "—" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_mon_1",
    day: "Monday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "ETE 4111",
    courseTitle: "ETE 4111",
    type: "theory",
    teacherInitials: ["RKH"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_mon_2",
    day: "Monday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "ETE 4113",
    courseTitle: "ETE 4113",
    type: "theory",
    teacherInitials: ["MFS"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_mon_3",
    day: "Monday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 41XX",
    courseTitle: "ETE 41XX",
    type: "theory",
    teacherInitials: ["MKH", "RTM"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_mon_4",
    day: "Monday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "ETE 4118",
    courseTitle: "Computer Lab",
    type: "lab",
    teacherInitials: ["HS"],
    room: { roomLabel: "Computer Lab" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_mon_7",
    day: "Monday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 4100",
    courseTitle: "Project & Thesis",
    type: "project",
    teacherInitials: ["—"],
    room: { roomLabel: "—" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_tue_1",
    day: "Tuesday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "ETE 4117",
    courseTitle: "ETE 4117",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_tue_2",
    day: "Tuesday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "ETE 4115",
    courseTitle: "ETE 4115",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_tue_3",
    day: "Tuesday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 4113",
    courseTitle: "ETE 4113",
    type: "theory",
    teacherInitials: ["MFS"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_tue_4",
    day: "Tuesday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "ETE 4114",
    courseTitle: "DSP LAB",
    type: "lab",
    teacherInitials: ["MFS"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_wed_3",
    day: "Wednesday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 4115",
    courseTitle: "ETE 4115",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_wed_4",
    day: "Wednesday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 4117",
    courseTitle: "ETE 4117",
    type: "theory",
    teacherInitials: ["MFS"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_wed_5",
    day: "Wednesday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 4113",
    courseTitle: "ETE 4113",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "Seminar" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },
  {
    _id: "21_wed_7",
    day: "Wednesday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 4112",
    courseTitle: "DSP LAB",
    type: "lab",
    teacherInitials: ["RKH"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "all",
    series: 21,
    semester: "odd",
  },

  // ── Series 22, Even Semester ─────────────────────────────────────────────
  {
    _id: "22_sat_4",
    day: "Saturday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 3111",
    courseTitle: "Digital  Communication",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sat_5",
    day: "Saturday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 3117",
    courseTitle: "Control System",
    type: "theory",
    teacherInitials: ["FZA"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sat_6",
    day: "Saturday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 3115",
    courseTitle: "Numerical Methods",
    type: "theory",
    teacherInitials: ["AM"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sat_7",
    day: "Saturday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "CSE 3154",
    courseTitle: "Web Programming",
    type: "lab",
    teacherInitials: ["AIS"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "1st30",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sun_1",
    day: "Sunday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "ETE 3113",
    courseTitle: "Microwave Engineering",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sun_2",
    day: "Sunday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "ETE 3111",
    courseTitle: "Digital  Communication",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sun_3",
    day: "Sunday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 3115",
    courseTitle: "Numerical Methods",
    type: "theory",
    teacherInitials: ["AM"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_sun_7",
    day: "Sunday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 3118",
    courseTitle: "Computer LAB",
    type: "lab",
    teacherInitials: ["FZA"],
    room: { roomLabel: "Computer LAB" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_mon_1",
    day: "Monday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "EEE 3154",
    courseTitle: "DSP LAB",
    type: "lab",
    teacherInitials: ["RA"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_mon_4",
    day: "Monday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 3111",
    courseTitle: "Digital  Communication",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_mon_5",
    day: "Monday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "EEE 3153",
    courseTitle: "Power System",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_mon_6",
    day: "Monday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 3113",
    courseTitle: "Microwave Engineering",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_mon_7",
    day: "Monday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 3112",
    courseTitle: "Communication Lab",
    type: "lab",
    teacherInitials: ["ST"],
    room: { roomLabel: "Communication Lab" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_tue_1",
    day: "Tuesday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "CSE 3154",
    courseTitle: "Web Programming",
    type: "lab",
    teacherInitials: ["AIS"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "2nd30",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_tue_4",
    day: "Tuesday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 3117",
    courseTitle: "Control System",
    type: "theory",
    teacherInitials: ["FZA"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_tue_5",
    day: "Tuesday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 3113",
    courseTitle: "Microwave Engineering",
    type: "theory",
    teacherInitials: ["ST"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_tue_6",
    day: "Tuesday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "EEE 3153",
    courseTitle: "Power System",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_tue_7",
    day: "Tuesday",
    startPeriod: 7,
    periodSpan: [7,8, 9],
    courseCode: "ETE 3116",
    courseTitle: "DSP LAB",
    type: "lab",
    teacherInitials: ["RTM"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_wed_4",
    day: "Wednesday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 3117",
    courseTitle: "Control System",
    type: "theory",
    teacherInitials: ["FZA"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_wed_5",
    day: "Wednesday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "EEE 3153",
    courseTitle: "Power System",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_wed_6",
    day: "Wednesday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 3115",
    courseTitle: "Numerical Methods",
    type: "theory",
    teacherInitials: ["AM"],
    room: { roomLabel: "R 302" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },
  {
    _id: "22_wed_7",
    day: "Wednesday",
    startPeriod: 7,
    periodSpan: [7,8, 9],
    courseCode: "ETE 3114",
    courseTitle: "Microwave Lab",
    type: "lab",
    teacherInitials: ["ST"],
    room: { roomLabel: "Microwave Lab EEE Building" },
    batchScope: "all",
    series: 22,
    semester: "odd",
  },

  // ── Series 23, Odd Semester ─────────────────────────────────────────────
  {
    _id: "23_sat_1",
    day: "Saturday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "ETE 2115",
    courseTitle: "ETE 2115",
    type: "theory",
    teacherInitials: ["NIN"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sat_2",
    day: "Saturday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "ETE 2115",
    courseTitle: "ETE 2115",
    type: "theory",
    teacherInitials: ["NIN"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sat_3",
    day: "Saturday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 2113",
    courseTitle: "ETE 2113",
    type: "theory",
    teacherInitials: ["MKH"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sat_4",
    day: "Saturday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "ETE 2112",
    courseTitle: "ELECTRONICS LAB",
    type: "lab",
    teacherInitials: ["HS"],
    room: { roomLabel: "ELECTRONICS LAB" },
    batchScope: "1st30",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sat_7",
    day: "Saturday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 2114",
    courseTitle: "Communication Lab",
    type: "lab",
    teacherInitials: ["MKH"],
    room: { roomLabel: "Communication Lab" },
    batchScope: "2nd30",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sun_1",
    day: "Sunday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "ETE 2114",
    courseTitle: "Communication Lab",
    type: "lab",
    teacherInitials: ["MKH"],
    room: { roomLabel: "Communication Lab" },
    batchScope: "1st30",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sun_4",
    day: "Sunday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 2115",
    courseTitle: "ETE 2115",
    type: "theory",
    teacherInitials: ["NIN"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sun_5",
    day: "Sunday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 2113",
    courseTitle: "ETE 2113",
    type: "theory",
    teacherInitials: ["MKH"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sun_6",
    day: "Sunday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "Math 2115",
    courseTitle: "Math 2115",
    type: "theory",
    teacherInitials: ["MSR"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_sun_7",
    day: "Sunday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 2112",
    courseTitle: "ELECTRONICS LAB",
    type: "lab",
    teacherInitials: ["HS"],
    room: { roomLabel: "ELECTRONICS LAB" },
    batchScope: "2nd30",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_mon_3",
    day: "Monday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 2111",
    courseTitle: "ETE 2111",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_mon_4",
    day: "Monday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "CSE 2153",
    courseTitle: "CSE 2153",
    type: "theory",
    teacherInitials: ["RKH"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_mon_5",
    day: "Monday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "Math 2115",
    courseTitle: "Math 2115",
    type: "theory",
    teacherInitials: ["MSR"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_mon_7",
    day: "Monday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 2116",
    courseTitle: "DSP Lab",
    type: "lab",
    teacherInitials: ["NIN"],
    room: { roomLabel: "DSP Lab" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_tue_1",
    day: "Tuesday",
    startPeriod: 1,
    periodSpan: [1, 2, 3],
    courseCode: "CSE 2154",
    courseTitle: "Computer LAB",
    type: "lab",
    teacherInitials: ["RKH"],
    room: { roomLabel: "Computer LAB" },
    batchScope: "2nd30",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_tue_4",
    day: "Tuesday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 2113",
    courseTitle: "ETE 2113",
    type: "theory",
    teacherInitials: ["MKH"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_tue_5",
    day: "Tuesday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "CSE 2153",
    courseTitle: "CSE 2153",
    type: "theory",
    teacherInitials: ["RKH"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_tue_6",
    day: "Tuesday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 2111",
    courseTitle: "ETE 2111",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_tue_7",
    day: "Tuesday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 2110",
    courseTitle: "Computer LAB",
    type: "lab",
    teacherInitials: ["ST"],
    room: { roomLabel: "Computer LAB" },
    batchScope: "1st30",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_wed_1",
    day: "Wednesday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "Math 2115",
    courseTitle: "Math 2115",
    type: "theory",
    teacherInitials: ["MHR"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_wed_2",
    day: "Wednesday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "CSE 2153",
    courseTitle: "CSE 2153",
    type: "theory",
    teacherInitials: ["RKH"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_wed_3",
    day: "Wednesday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 2111",
    courseTitle: "ETE 2111",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "R 303" },
    batchScope: "all",
    series: 23,
    semester: "odd",
  },
  {
    _id: "23_wed_4",
    day: "Wednesday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "CSE 2154 / ETE 2110",
    courseTitle: "Computer / DSP LAB",
    type: "lab",
    teacherInitials: ["RKH", "ST"],
    room: { roomLabel: "Computer / DSP LAB" },
    batchScope: "all", // 1st30 and 2nd30 combined block
    series: 23,
    semester: "odd",
  },

  // ── Series 24, Even Semester ─────────────────────────────────────────────
  {
    _id: "24_sat_1",
    day: "Saturday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "EEE 1253",
    courseTitle: "EEE 1253",
    type: "theory",
    teacherInitials: ["MHR"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sat_2",
    day: "Saturday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "EEE 1253",
    courseTitle: "EEE 1253",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sat_3",
    day: "Saturday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "Hum 1215",
    courseTitle: "Hum 1215",
    type: "theory",
    teacherInitials: ["KF"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sat_4",
    day: "Saturday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "CSE 1254",
    courseTitle: "DSP LAB",
    type: "lab",
    teacherInitials: ["AIS"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "1st30",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sat_7",
    day: "Saturday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 1212",
    courseTitle: "ELECTRONICS LAB",
    type: "lab",
    teacherInitials: ["HS"],
    room: { roomLabel: "ELECTRONICS LAB" },
    batchScope: "2nd30",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sun_4",
    day: "Sunday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "ETE 1211",
    courseTitle: "ETE 1211",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sun_5",
    day: "Sunday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 1213",
    courseTitle: "ETE 1213",
    type: "theory",
    teacherInitials: ["MFS", "NIN"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sun_6",
    day: "Sunday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "EEE 1253",
    courseTitle: "EEE 1253",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_sun_7",
    day: "Sunday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "CSE 1254",
    courseTitle: "DSP LAB",
    type: "lab",
    teacherInitials: ["AIS"],
    room: { roomLabel: "DSP LAB" },
    batchScope: "2nd30",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_mon_1",
    day: "Monday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "ETE 1211",
    courseTitle: "ETE 1211",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_mon_2",
    day: "Monday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "Hum 1215",
    courseTitle: "Hum 1215",
    type: "theory",
    teacherInitials: ["TKS"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_mon_3",
    day: "Monday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "Math 1215",
    courseTitle: "Math 1215",
    type: "theory",
    teacherInitials: ["MRK"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_mon_4",
    day: "Monday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "ETE 1214",
    courseTitle: "ELECTRONICS LAB",
    type: "lab",
    teacherInitials: ["MFS", "NIN"],
    room: { roomLabel: "ELECTRONICS LAB" },
    batchScope: "1st30",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_tue_1",
    day: "Tuesday",
    startPeriod: 1,
    periodSpan: [1],
    courseCode: "EEE 1253",
    courseTitle: "EEE 1253",
    type: "theory",
    teacherInitials: ["RA"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_tue_2",
    day: "Tuesday",
    startPeriod: 2,
    periodSpan: [2],
    courseCode: "Math 1215",
    courseTitle: "Math 1215",
    type: "theory",
    teacherInitials: ["MHR"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_tue_3",
    day: "Tuesday",
    startPeriod: 3,
    periodSpan: [3],
    courseCode: "ETE 1213",
    courseTitle: "ETE 1213",
    type: "theory",
    teacherInitials: ["MFS", "NIN"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_tue_4",
    day: "Tuesday",
    startPeriod: 4,
    periodSpan: [4, 5, 6],
    courseCode: "ETE 1214",
    courseTitle: "ELECTRONICS LAB",
    type: "lab",
    teacherInitials: ["MFS", "NIN"],
    room: { roomLabel: "ELECTRONICS LAB" },
    batchScope: "2nd30",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_tue_7",
    day: "Tuesday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "ETE 1212",
    courseTitle: "ELECTRONICS LAB",
    type: "lab",
    teacherInitials: ["HS"],
    room: { roomLabel: "ELECTRONICS LAB" },
    batchScope: "1st30",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_wed_4",
    day: "Wednesday",
    startPeriod: 4,
    periodSpan: [4],
    courseCode: "Hum 1215",
    courseTitle: "Hum 1215",
    type: "theory",
    teacherInitials: ["KF"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_wed_5",
    day: "Wednesday",
    startPeriod: 5,
    periodSpan: [5],
    courseCode: "ETE 1213",
    courseTitle: "ETE 1213",
    type: "theory",
    teacherInitials: ["MFS", "NIN"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_wed_6",
    day: "Wednesday",
    startPeriod: 6,
    periodSpan: [6],
    courseCode: "ETE 1211",
    courseTitle: "ETE 1211",
    type: "theory",
    teacherInitials: ["HS"],
    room: { roomLabel: "R 304" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
  {
    _id: "24_wed_7",
    day: "Wednesday",
    startPeriod: 7,
    periodSpan: [7, 8, 9],
    courseCode: "EEE 1254",
    courseTitle: "Machine LAB",
    type: "lab",
    teacherInitials: ["RA"],
    room: { roomLabel: "Machine LAB" },
    batchScope: "all",
    series: 24,
    semester: "even",
  },
];
module.exports = { ALL_SLOTS };